backend:
  name: github
  repo: gibbyn05/altiild
  branch: main
  auth_endpoint: api/auth

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: pages
    label: Sider
    folder: content/pages
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Description
        name: description
        widget: text
      - label: Content
        name: body
        widget: markdown
      - label: Publish Date
        name: publishedAt
        widget: datetime

  - name: services
    label: Tjenester
    folder: content/services
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Description
        name: description
        widget: text
      - label: Content
        name: body
        widget: markdown
      - label: Image
        name: image
        widget: image
      - label: Publish Date
        name: publishedAt
        widget: datetime

  - name: posts
    label: Blog Posts
    folder: content/posts
    create: true
    slug: "{{slug}}"
    format: json
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Description
        name: description
        widget: text
      - label: Content
        name: body
        widget: markdown
      - label: Featured Image
        name: image
        widget: image
      - label: Publish Date
        name: publishedAt
        widget: datetime
      - label: Author
        name: author
        widget: string
